name: kitsu_deck_dash
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.0.17
  system_tray: ^2.0.2
  web_socket_channel: ^2.3.0
  window_manager: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_icons:
  windows:
    generate: true
    image_path: "assets/images/flutter_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
    adaptive_icon_background: "#FFFFFF" # default: #FFFFFF
  macos:
    generate: true
    image_path: "assets/images/flutter_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
    adaptive_icon_background: "#FFFFFF" # default: #FFFFFF
