name: Flutter Desktop Build

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build app for Windows
        run: flutter build windows --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: KitsuDeckDash-windows
          path: build/windows/Release/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y appindicator3-0.1 libappindicator3-dev
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          channel: stable
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build app for Linux
        run: flutter build linux --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: KitsuDeckDash-linux
          path: build/linux/Release/

  build-macos-x64:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build app for macOS x64
        run: flutter build macos --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: KitsuDeckDash-macos
          path: build/macos/Build/Products/Release/
